# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Metadata
mod_id=fireworkfrenzy
mod_description=An overhaul to Firework Rockets and how the Crossbow makes use of them
mod_display_name=Firework Frenzy
sources_url=https://github.com/CammiePone/Firework-Frenzy
issues_url=https://github.com/CammiePone/Firework-Frenzy/issues
license_url=https://github.com/CammiePone/Firework-Frenzy/blob/HEAD/LICENSE
discord_url=https://cammiescorner.dev/discord
homepage_url=https://www.curseforge.com/projects/520310
maven_group_id=dev.cammiescorner.fireworkfrenzy

# Dependencies are managed at gradle/libs.versions.toml
